### ISSUE TITLE
Overnode launch fails with SELinux.

### ISSUE THREAD

**Issue by avkonst** [overnode-org/overnode#39]
As @jtagcat discovered it. 
This ticket is created to capture the guidelines in the documentation how to work around it

**Comment by avkonst** [comment]
@jtagcat could you please write brief instructions on how to configure SELinux so docker run via weave works? You can post it in this ticket and I will incorporate it to the documentation after.
Thanks,
Andrey

**Comment by jtagcat** [comment]
tldr :thonk:

I haven't found any other way to get it working than setenforce=0.

see https://github.com/weaveworks/weave/issues/3572#issuecomment-669631684 and other links there for pretty much all the information I have

nothing has worked so far..

Leaving this open until I get a working setup, I don't want to be that guy who writes 'enforce=0 to make it work'.
