### ISSUE TITLE
Support for SIGHUP/Config reload.

### ISSUE THREAD

**Issue by jtagcat** [overnode-org/overnode#54]
Allow sending 'hello app, please reload your configuration' to all nodes. This can be done locally with `docker kill -sHUP subconfig_appname_1`

**Comment by jtagcat** [comment]
Seems to be implemented via on kill command, going to test soon™ as user reported it didn't work…

**Comment by avkonst** [comment]
I think it should work. I have sent custom signals via kill command

**Comment by jtagcat** [comment]
Tested, indeed does work (problem of rtfm).
